<?php echo '<?php' ?>


// Generated by Transtable - <?php echo date('Y-m-d H:i:s') ?>


<?php

function echo_translation_array($translations, $var_name, $arr_level = ''){
	
	foreach ($translations as $index => $translation){
		
		$arr_level1 = $arr_level . "['" . $index . "']";
		
		if(is_array($translation)){
			echo_translation_array($translation, $var_name, $arr_level1);
		}
		else
			echo '$' . $var_name . $arr_level1 . " = '" . addslashes($translation) . "';\n";
	}
	
}

echo_translation_array($t, $var_name);

