<?php

// Generated by Transtable - 2013-03-20 03:47:49

$t['sdfsdfsdfsdfsdf'] = 'sadfasdfasdfasdfasdfLog in by using electronic identity in the Eduroam system &gt;&gt;';
$t['sfgh'] = 'Faculty of<strong> Mechanical Engineeri</strong>ng and Naval Architecture';
$t['zzzzz'] = 'dsf<sub>fgdgsdfgsdfg</sub>sdfasdfasd<sup>fasdfasd</sup>f asd fasd fsdfsdfsdfsdf asdfasd fasdf asdf asdf asfsadfa sdfsdfsdf';
