<?php

// Generated by Transtable - 2013-03-19 18:41:48

$t['sdfsdfsdfsdfsdf'] = 'sadfasdfasdfasdfasdfLog in by using electronic identity in the Eduroam system &gt;&gt;';
$t['sfgh'] = 'Faculty of Mechanical Engineering and Naval Architecture';
$t['zzzzz'] = 'dsf<sub>fgdgsdfgsdfg</sub>sdfasdfasd<sup>fasdfasd</sup>f asd fasd fsdfsdfsdfsdf asdfasd fasdf asdf asdf asfsadfa sdfsdfsdf';
