<?php

// Generated by Transtable - 2013-03-14 18:50:02

$t['user'] = 'user';
$t['sdfsdfsdfsdfsdf'] = 'Log in by using electronic identity in the Eduroam system &gt;&gt;';
$t['sdfsdfsdffsb'] = 'Faculty of Mechanical Engineering and Naval Architecture';
$t['zzzzzzzzzzzz'] = 'sdfasdfasdfasdfasdf asd fasd fsdfsdfsdfsdf';
$t['sssdsdsd'] = 'asdasdasdasdasdasd';
