<?php

// Generated by Transtable - 2013-03-20 03:52:55

$t['main_title1'] = 'Zagreb Point';
$t['main_title2'] = 'apartamentos';
$t['main_title_subtitle'] = 'Apartamentos para estancias breves en Zagreb';
$t['main_menu1'] = 'Apartamento <strong>1</strong>';
$t['main_menu2'] = 'Apartamento <strong>2</strong>';
$t['main_menu3'] = 'Apartamento <strong>3</strong>';
$t['show_on_map'] = 'Mostrar en la mapa...';
$t['more_details'] = 'Más información &gt;&gt;';
$t['reservation'] = 'Reserva y contacto';
$t['description'] = 'Descripción';
$t['price'] = 'Precio';
$t['days_short']['0'] = 'lun';
$t['days_short']['1'] = 'mar';
$t['days_short']['2'] = 'mie';
$t['days_short']['3'] = 'jue';
$t['days_short']['4'] = 'vie';
$t['days_short']['5'] = 'sab';
$t['days_short']['6'] = 'dom';
$t['months']['0'] = 'enero';
$t['months']['1'] = 'febrero';
$t['months']['2'] = 'marzo';
$t['months']['3'] = 'abril';
$t['months']['4'] = 'mayo';
$t['months']['5'] = 'junio';
$t['months']['6'] = 'julio';
$t['months']['7'] = 'agosto';
$t['months']['8'] = 'septiembre';
$t['months']['9'] = 'octubre';
$t['months']['10'] = 'noviembre';
$t['months']['11'] = 'diciembre';
$t['months_short']['0'] = 'ene';
$t['months_short']['1'] = 'feb';
$t['months_short']['2'] = 'mar';
$t['months_short']['3'] = 'abr';
$t['months_short']['4'] = 'may';
$t['months_short']['5'] = 'jun';
$t['months_short']['6'] = 'jul';
$t['months_short']['7'] = 'ago';
$t['months_short']['8'] = 'sep';
$t['months_short']['9'] = 'oct';
$t['months_short']['10'] = 'nov';
$t['months_short']['11'] = 'dec';
$t['free'] = 'disponible';
$t['ocupied'] = 'reservado';
$t['next_month'] = 'próximo mes';
$t['prev_month'] = 'mes anterior';
$t['choose'] = 'seleccione';
$t['send'] = 'Envíe su solicitud ';
$t['form_name'] = 'Su nombre:';
$t['form_validator_name'] = 'Ingrese su nombre';
$t['form_email'] = 'E-mail:';
$t['form_validator_email'] = 'Ingrese su E-mail';
$t['form_validator_email2'] = 'Ingrese su E-mail otra vez';
$t['form_email2'] = 'E-mail otra vez:';
$t['form_arival_date'] = 'Fecha de llegada:';
$t['form_validator_date'] = 'Seleccione la fecha de llegada al hacer clic en el calendario';
$t['form_days'] = 'Días de estancia:';
$t['form_validator_days'] = 'Seleccione el número de noches';
$t['form_message'] = 'Su mensaje:';
$t['form_validator_message'] = 'Escriba su mensaje';
$t['reservation_form'] = 'Solicitud de reserva:';
$t['form_validator_date_hint'] = 'Haga clic en un día disponible en el calendario';
$t['tel_email'] = 'Teléfono y E-mail:';
$t['message_sent'] = 'El mensaje ha sido enviado. Gracias por su consulta. Nos pondremos en contacto con usted en breve.';
$t['message_sent_err'] = 'Error al enviar mensaje. Inténtelo de nuevo o escriba al correo electrónico zagrebapartment@gmail.com';
$t['tel'] = 'Teléfono:';
$t['email'] = 'E-mail:';
$t['location'] = 'Ubicación';
$t['zoom'] = 'Aumentar';
$t['picture'] = 'foto';
$t['from'] = 'de';
$t['till'] = 'hasta';
$t['From'] = 'de';
$t['per_night'] = 'por día';
$t['address'] = 'Dirección:';
$t['address1'] = '<strong>Dirección:</strong><br />';
$t['appartment_address'] = 'Dirección del apartamento :';
$t['room_no'] = 'Habitaciones:';
$t['bed_no'] = 'Camas:';
$t['area'] = 'Área:';
$t['floor'] = 'Piso:';
$t['persons'] = 'Personas:';
$t['check_in'] = 'Llegada:';
$t['check_out'] = 'Salida:';
$t['legend'] = 'Leyenda:';
$t['occupied'] = 'Reservado';
$t['plan'] = 'Plano del piso';
$t['floor1'] = 'Piso';
$t['apartment_plan'] = 'Plano del piso';
$t['price1'] = 'Precio:';
$t['gps_coordinates'] = 'GPS:';
$t['book_online'] = 'Reserve On-line &gt;&gt;';
$t['facebook_icon'] = 'Join us on Facebook';
$t['apartment1']['index_header'] = 'Apartamento 1: Rupa pod oblacima';
$t['apartment1']['index_description_title'] = 'Acogedor apartamento con una gran vista de toda la ciudad!';
$t['apartment1']['index_description'] = '
<ul>
	<li>Parking, internet gratuito, DVD…</li>
	<li>10 minunuos desde el centro de la ciudad.</li>
	<li>Hermosa vista de toda la ciudad de Zagreb</li>
</ul>
';
$t['apartment1']['address'] = 'Selska cesta 34<br />
10110 Zagreb, Croacia';
$t['apartment1']['map_description'] = 'Selska cesta 34<br />
10110 Zagreb, Croacia<br />
<strong>Coordenadas GPS:</strong><br />
45.808090, 15.942096';
$t['apartment1']['map_title'] = 'Apartamento 1: Rupa pod oblacima';
$t['apartment1']['description'] = '
<p>Si está considerando una estancia corta o larga en Zagreb, le ofrecemos un <strong>alojamiento agradable y acogedor</strong> de tres estrellas, cerca del centro de Zagreb, a <strong>sólo diez minutos de la plaza principal</strong> en tranvía.</p>
</p>Nuestro alojamiento esta en la planta 14 de un edificio residencial, <strong>orientado hacia el sureste</strong>, con una <strong>hermosa vista sobre la ciudad</strong>. El alojamiento está <strong>encantadoramente decorado</strong> en un estilo juvenil, que lo hace <strong>ideal para los estudiantes, jóvenes</strong>, gente de negocios y otros.</p>
</p>Ofrecemos alojamiento para un máximo de <strong>4-5 personas</strong> en un apartamento <strong>completamente amueblado y equipado</strong>, que incluye una entrada grande, una sala de estar espaciosa, una habitación con cama doble, cocina con comedor y un bano, espacio más que suficiente para una estancia agradable y confortable.</p>
</p>Proveemos camas, ropa de cama y toallas para <strong>4-5 personas</strong>.</p>
';
$t['apartment1']['services'] = '

<ul class=\\\\\\\\\\\\\\\\\\\\\"ul_ok\\\\\\\\\\\\\\\\\\\\\">

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Camas</li>

	<li></i>1 cama doble (160/215)</li>
	<li></i>2 sofa-cama (90/220)</li>
	<li></i>1 cama plegable (80/190)</li>
	<li>Cuna (a petición) </li>


	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Entretenimiento y comodidad</li>

	<li>internet WIFI de alta velocidad</li>
	<li>TV por cable, CD/DVD </li>	
	<li>aire acondicionado</li>
	<li>balcón (vista de toda la ciudad)</li>

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Cuarto de bano</li>

	<li>sábanas y toallas</li>
	<li>secadora de pelo</li>
	<li>lavadora</li>
	<li>plancha, tabla de planchar y tendedero</li>

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Cocina</li>

	<li>nevera, horno, cocina (electricidad y gas )</li>
	<li>batidora</li>
	<li>maquina de café</li>
	<li>microondas</li>	
	<li>aspiradora</li>
	
	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Edificio</li>

	<li>plaza de aparcamiento – gratuita – en la esplanada grande situada junto al edificio.</li>
	<li>ascensor</li>
</ul>
';
$t['apartment1']['pricelist_comment'] = '
<ul>
	<li>El apartamento se alquila por día, el número de personas que lo alquilen no modifica el precio.</li>
	<li>Para uno y dos días de estancia el precio se incrementa en 10 €</li>
	<li>En el período de Navidad y de Ano Nuevo el precio se incrementa para estancias menores a 5 días</li>
</ul>
';
$t['apartment1']['reservation_text'] = '
<p>Puede hacer sus reservas en línea o puede usted pagar al menos 50 € por transferencia bancaria.<br />
Si ustedes llegan en los próximos 2-3 días, el pago de la reserva no es necesario</p>
';
$t['apartment1']['location_description'] = '
<h3>Conexiones de transporte público</h3>
<p>Cerca del apartamento hay paradas de autobuses; de la línea 109 (Črnomerec-Dugave; que conecta el noroeste y el suroeste de la ciudad), y la línea 118 (Trg Mažuraničevih-Voltino; que conecta al este y el oeste de la ciudad – es la forma más rápida de llegar al centro !en diez minutos!), tambien  paradas de tranvía (cinco minutos a pie) de la línea 2, 6, 11 y línea nocturna 31</p>
<h3>Desde la estación central de autobuses</h3>
<p>Desde la terminal de autobuses (Držićeva ulica) pueden llegar al apartamento directamente en tranvía (línea 2 y 6) dirección \\\\\\\\\\\\\\\\\\\\\"Črnomerec\\\\\\\\\\\\\\\\\\\\\". Este trayecto dura de quince a veinte minutos. Hay que bajarse en la estación \\\\\\\\\\\\\\\\\\\\\"Sveti Duh\\\\\\\\\\\\\\\\\\\\\"(penúltima de la línea), y se tiene que andar cinco minutos a pie por la calle „Selska cesta“ hasta el apartamento.</p>
<h3>Desde la estación principal de trenes</h3>
<p>La estación de tren está a sólo tres paradas de tranvía desde la terminal central de autobuses. Por eso se pueden utilizar las mismas líneas de tranvía (2 y 6) dirección \\\\\\\\\\\\\\\\\\\\\"Črnomerec\\\\\\\\\\\\\\\\\\\\\". La parada de tranvía está delante de la estación de tren. Hay que bajarse en la estación \\\\\\\\\\\\\\\\\\\\\"Sveti Duh\\\\\\\\\\\\\\\\\\\\\" (penúltima), y hay que andar cinco minutos a pie por la calle „Selska cesta“ hasta el apartamento.</p>
<h3>Desde el aeropuerto</h3>
<p>Desde el aeropuerto se puede llegar en Croatia Airlines Transporte, que está conduciendo a la terminal central de autobuses. El billete cuesta 30 HRK (€ 4/ $ 6). El trayecto desde el aeropuerto hasta la terminal central de autobuses tarda unos treinta minutos. El primer transbordador sale del aeropuerto a las 05:00 AM, el último a las 20:00. Después de las 20:00 el transbordador sale del aeropuerto después de cada aterrizaje de Croatia Airlines. El cómo llegar desde la terminal de autobuses al apartamento esta indicado anteriormente.<p>
<p>Para más detalles, por favor, siga el enlace: <a href=\\\\\\\\\\\\\\\\\\\\\"http://www.plesoprijevoz.hr\\\\\\\\\\\\\\\\\\\\\">plesoprijevoz.hr</a> (en croata o Inglés)</p>
<h3>En taxi</h3>
<p>Si ustedes desean tomar un taxi, por favor recuerde nuestra dirección – Selska cesta 34. Muchos de los taxis se ecuentran en frente de la terminal central de autobuses, la estación principal de trenes, así como el aeropuerto de Pleso.</p>
<p>El trayecto desde la terminal central de autobuses o la estación principal de tren le costará alrededor de  30 HRK (&#8364; 4/ $6). El trayecto desde el aeropuerto le costará alrededor de HRK 100 - 160 (&#8364; 13-21 / $ 16-25).</p>
';
$t['apartment2']['index_header'] = 'Apartamento 2: Penthouse Zagreb';
$t['apartment2']['index_description_title'] = 'Ático espacioso y lujoso, ideal para familias y gente de negocios.';
$t['apartment2']['index_description'] = '
<ul>
	<li>dos plazas de aparcamiento privadas, WIFI, DVD...</li>
	<li>barrio tranquilo y cerca de centro de la ciudad</li>
</ul>
';
$t['apartment2']['address'] = '
II. Vrbik 14<br />
10000 Zagreb, Croatia
';
$t['apartment2']['map_description'] = '
II. Vrbik 14<br />
10000 Zagreb, Croatia

<br />
<strong> Coordenadas GPS:</strong><br />
45.795941, 15.967727
';
$t['apartment2']['map_title'] = 'Apartamento 2: Penthouse Zagreb';
$t['apartment2']['description'] = '
<p>Si ustedes están buscando un apartamento <strong>lujoso y espacioso</strong> en <strong>el centro de Zagreb</strong>, si desean una estancia larga o más corta, podemos ofrecerles un  <strong>duplex de 120m2  de cuatro estrellas</strong>, cerca del centro de la ciudad, a  <strong>sólo 10 minutos de la plaza principal</strong>  en tranvía. (Jelačić plaza)</p>
<p>El apartamento tiene  <strong>dos plantas</strong>. La primera planta tiene un amplio hall de entrada con un balcón, un bano y un dormitorio, mientras que la sala de estar, la cocina y el comedor, el estudio, el dormitorio principal, el bano principal y la terraza están en la segunda planta.</p>
<p> <strong>Dos habitaciones con banos</strong> separadas en ambas plantas les darán toda  <strong>la privacidad</strong> que necesiten, mientras que la  <strong>amplia sala de estar y comedor</strong> le proporcionarán un lugar para pasar un agradable rato juntos hasta altas horas de la noche.</p>
<p>El apartamento es  <strong>ideal para familias y hombres de negocios</strong> o para sus socios de negocios durante sus estancias en Zagreb.</p>
<p><strong>Dos plazas de aparcamiento privadas</strong> les permitirán estacionar su vehículo, y también servirá como un espacio de estacionamiento privado para sus amigos o socios de negocios.</p>
<p>Ofrecemos camas, ropa de cama y toallas para 5 personas.</p>';
$t['apartment2']['services'] = '

<ul class=\\\\\\\\\\\\\\\\\\\\\"ul_ok\\\\\\\\\\\\\\\\\\\\\">

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Camas</li>
	
	<li>1 cama doble (160/200)</li>
	<li>2 camas individuales (con la posibilidad de unirse en una cama doble)</li>
	<li>1 cama supletoria</li>
	<li>Cuna (a petición) </li>
	
	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Entretenimiento y comodidad</li>
	
	<li>internet WIFI de alta velocidad</li>
	<li>cable TV, CD/DVD(Televisores en los dormitorios y sala de estar)</li>	
	<li>aire acondicionado</li>
	<li>Terraza y balcón</li>
	
	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Cuarto de bano</li>

	<li>sábanas y toallas</li>
	<li>secadora de pelo</li>
	<li>lavadora</li>
	<li>plancha, tabla de planchar y tendedero</li>

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Cocina</li>

	<li>nevera, horno, cocina (electricidad y gas )</li>
	<li>batidora</li>
	<li>maquina de café</li>
	<li>microondas</li>	
	<li>aspiradora</li>

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Edificio</li>

	<li>Dos plazas de aparcamiento privada</li>
	<li>ascensor</li>
</ul>
';
$t['apartment2']['pricelist_comment'] = '
<ul>
	<li>El apartamento se alquila por día, el número de personas que lo alquilan no cambia el precio.</li>
	<li>Para uno y dos días de estancia el precio es de 10 € más alta</li>
	<li>En el período de la Navidad y de Ano Nuevo el precio se incrementa para estancia que es menos de 5 días</li>
</ul>
';
$t['apartment2']['reservation_text'] = '
<p>Para hacer sus reservaciones se pueden reservar en línea o usted puede pagar al menos 50 € por transferencia bancaria.<br />
Si ustedes llegan en próximos 2-3 días el pago de la reserva no es necesaria</p>
';
$t['apartment2']['location_description'] = '
<h3>Conexiones de transporte público</h3>
<p>El apartamento está en un barrio de Zagreb llamado Vrbik, a 5 minutos a pie de las paradas de tranvía \\\\\\\\\\\\\\\\\\\\\"fakultet Učiteljski\\\\\\\\\\\\\\\\\\\\\" (14,5,4,17) y \\\\\\\\\\\\\\\\\\\\\"Vrbik\\\\\\\\\\\\\\\\\\\\\" (5,13,3). Solo 10 min en tranvia hasta el centro.</p>
<h3>Desde la estación central de autobuses</h3>
<p>Desde la terminal de autobuses (calle „Držićeva ulica“) pueden llegar al apartamento directamente en la línea 5 de tranvía, dirección „Prečko“. Hay que bajarse en la estación „Vrbik“ y de allí son unos 5 minutos a pie caminando por las calles „Fausta Vrančića“ y „II Vrbik“.</p>
<h3>Desde la estación principal de trenes</h3>
<p>La forma más rápida de llegar desde la estación central de tren es andando. Desciendan por las escaleras del paso „Importane Centar“ y caminen hasta la avenida „avenija Vukovar“, sigan  por la avenida hasta la parada de tranvía „Vrbik“, y luego por la calles de „Fausto Vrančić“ y  „II Vrbik“. El paseo dura aproximadamente 15 minutos.
Si lo desea, puede ir en tranvía en la línea 4, en dirección „Savski most“. Hay que bajar en la parada „Učiteljski fakultet“ y de allí hay unos 5 minutos a pie caminando en dirección de la plaza „Kninski trg“</p>
<h3>Desde el aeropuerto</h3>
<p>Croatia Airlines ofrece un servicio de transporte hasta la estación central de autobuses. El billete cuesta 30 HRK,(5€/ $6). El trayecto desde el aeropuerto es de unos treinta minutos. El primer autobús sale del aeropuerto a las 05:00 y el último a las 20:00 horas. Después de las 20:00 el autobús sale después de cada aterrizaje de Croatia Airlines. Para saber cómo llegar desde la estación central  de autobuses al apartamento miren el apartado anterior.</p>
<p>Para más detalles por favor siga el enlace: <a href=\\\\\\\\\\\\\\\\\\\\\"http://www.plesoprijevoz.hr\\\\\\\\\\\\\\\\\\\\\">plesoprijevoz.hr</a> (en croata o Inglés)</p>
<h3>En taxi</h3>
<p>Si ustedes desean tomar un taxi, por favor recuerde nuestra dirección – 2. Vrbik; 14. Muchos de los taxis se ecuentran en frente de la terminal central de autobuses, la estación principal de trenes, así como el aeropuerto de Pleso. </p
<p>El trayecto desde la terminal central de autobuses o la estación principal de tren le costará alrededor de  30 HRK (€4 / $6). El trayecto desde el aeropuerto le costará alrededor de HRK 100 - 160 (€13-26 / $16-25).</p>
';
$t['apartment3']['index_header'] = 'Apartamento 3: Central Point';
$t['apartment3']['index_description_title'] = 'Apartamento moderno en el centro de la ciudad, a distancia de pie de todas las atracciones principales';
$t['apartment3']['index_description'] = '
<ul>
	<li>cerca de la estación principal de tren y del centro comercial</li>
	<li>WIFI, DVD,...</li>
	<li>pocos minutos a pie de la plaza principal</li>
</ul>
';
$t['apartment3']['address'] = '
Miramarska 15b<br />
10000 Zagreb, Croatia
';
$t['apartment3']['map_description'] = '
Miramarska 15b<br />
10000 Zagreb, Croatia

<br />
<strong>> Coordenadas GPS:</strong><br />
45.808090, 15.942096
';
$t['apartment3']['map_title'] = 'Apartamento 3: Central Point';
$t['apartment3']['description'] = '
<p>?Debe usted considerar una estancia corta o larga en Zagreb, le ofrecemos un alojamiento <strong>agradable y acogedor</strong> en un condominio de <strong> tres estrellas </strong>, en el <strong> centro de Zagreb,  junto a la estación principal de tren </strong> a sólo 10 minutos a pie de la plaza principal (Plaza Jelacic).</p>
<p>Nuestro alojamiento es en el 2do piso de un edificio residencial, <strong> orientada de este a oeste </strong> que lo hace muy <strong> luminoso y acogedor </strong>. El alojamiento es, hermosamente amueblado, ideal para las <strong> familias y la gente de negocios </strong>.</p>
<p>El apartamento es adecuado para <strong> 4-5 personas </strong >e incluye un área de entrada, una sala de estar amplias con terraza, una habitación de doble-cama, cocina con comedor y un bano, todo lo cual hace más que un espacio necesario para una estancia agradable y confortable.</p>
<p><strong> La cocina grande y bien equipada </strong> con grandes ventanas hará una experiencia de cocinar agradable y la terraza en el lado este es perfecto para el café por la manana.</p>
<p><strong>  La posición central </strong > de la ciudad, junto a la estación de tren principal, le permitirá visitar casi todos los <strong>  lugares de interés turístico a pie </strong >, así que usted no dependerá de coche o transporte público.</p>
<p>Sin embargo, la ubicación está <strong>  muy bien conectada con transporte público </strong >, así que si usted va a necesitar llegar a otras partes de la ciudad puede contar con <strong>tranvía y numerosas líneas de autobús</strong > que paradas están a la vuelta de la esquina. (tranvías 2, 3, 5, 6, 11 y 13) </p>
';
$t['apartment3']['services'] = '

<ul class=\\\\\\\\\\\\\\\\\\\\\"ul_ok\\\\\\\\\\\\\\\\\\\\\">

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Camas</li>

	<li></i>cama doble (160/200)</li>
	<li></i>2 dobles sofa-camas (160/200)</li>
	<li>Cuna (a petición) </li>

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Entretenimiento y comodidad</li>

	<li>internet WIFI de alta velocidad</li>
	<li>cable TV, CD/DVD(Televisor en el dormitorio y la sala de estar)</li>	
	<li>aire acondicionado (en el dormitorio y la sala de estar)</li>
	<li>Terraza</li>

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Cuarto de bano</li>

	<li>sábanas y toallas</li>
	<li>secadora de pelo</li>
	<li>lavadora</li>
	<li>plancha, tabla de planchar y tendedero</li>

	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Cocina</li>

	<li>nevera, horno, cocina (electricidad y gas )</li>
	<li>batidora</li>
	<li>maquina de café</li>
	<li>microondas</li>	
	<li>aspiradora</li>
	<li>tostadora</li>
	
	
	<li class=\\\\\\\\\\\\\\\\\\\\\"title\\\\\\\\\\\\\\\\\\\\\">Edificio</li>

	<li> Aparcamiento - se cobra - al lado del edificio</li>
	<li> Aparcamiento - gratis - 300m del edificio</li>
	<li> ascensor</li>
</ul>
';
$t['apartment3']['location_description'] = '
<h3>Conexiones de transporte público</h3>
<p>El apartamento está situado <strong>cerca de la estación principal de trenes</strong>. En las cercanías hay paradas de tranvía para las líneas 2, 3, 4, 6, 11, y 13 y las paradas de autobús de las líneas de autobuses.</p>
<h3>Desde la estación central de autobuses</h3>
<p>Desde la terminal de autobuses (Drziceva ulica) Puede llegar a nosotros directamente en tranvía (línea 2 y 6) en dirección \\\\\\\\\\\\\\\\\\\\\"Crnomerec\\\\\\\\\\\\\\\\\\\\\". Es un viaje de cinco minutos. Te bajas en la tercera estación \\\\\\\\\\\\\\\\\\\\\"Željeznički kolodvor\\\\\\\\\\\\\\\\\\\\\", y desde allí tiene usted una caminata de cinco minutos a través de \\\\\\\\\\\\\\\\\\\\\"Importane\\\\\\\\\\\\\\\\\\\\\" pasaje.</p>
<h3>Desde la estación principal de trenes</h3>
<p>El apartamento está situado a sólo 5 minutos a pie a través de Importane pasaje. Al salir pasage Importane el primer edificio grande a la derecha es el edificio de apartamentos.</p>
<h3>Desde el aeropuerto</h3>
<p>Croatia Airlines ofrece un servicio de transporte hasta la estación central de autobuses. El billete cuesta 30 HRK,(5€/ $6). El trayecto desde el aeropuerto es de unos treinta minutos. El primer autobús sale del aeropuerto a las 05:00 y el último a las 20:00 horas. Después de las 20:00 el autobús sale tras cada aterrizaje de Croatia Airlines. Para saber cómo llegar desde la estación central  de autobuses al apartamento miren el apartado anterior.<p>
<p>Para más detalles por favor siga el enlace: <a href=\\\\\\\\\\\\\\\\\\\\\"http://www.plesoprijevoz.hr\\\\\\\\\\\\\\\\\\\\\">plesoprijevoz.hr</a> (en croata o Inglés)</p>
<h3>En taxi</h3>
<p>Si ustedes desean tomar un taxi, por favor recuerde nuestra dirección – Miramarska cesta 15b. Muchos taxis se localizan en frente de la terminal central de autobuses, la estación principal de trenes, así como el aeropuerto de Pleso. </p
<p>El trayecto desde la terminal central de autobuses le costará alrededor de  20 HRK (€3 / $4). El trayecto desde el aeropuerto le costará alrededor de HRK 100 - 160 (€13-26 / $16-25).</p>
';
