<?php

// Generated by Transtable - 2013-03-06 02:49:17

// Translations
$t['wwwwww'] = 'asdfasdfasdfasdf';
$t['wwwwwwwww_eee'] = 'asdfasdfasdfasdf';
$t['wwwwwwwww']['eee'] = 'asdfasdfasdfasdf';
$t['wwwwwwwww']['eeexx']['esssee'] = 'asdfasdfasdfasdf';
