<?php

// Generated by Transtable - 2013-03-15 18:19:42

$t['login_aai'] = 'Log in by using electronic identity in the Eduroam system &gt;&gt;';
$t['zzzzz'] = 'yxvcvyx yxc sdfasdfasdfasdfasdf asd fasd fsdfsdfsdfsdf';
$t['asdfasdfsssdsdsd'] = 'asdasdasdasdasdasd';
$t['sfgh'] = 'Faculty of Mcvxcvxcve yxc yxc yxc yxc yxc';
