<?php

// Generated by Transtable - 2013-03-13 01:20:26

$t['user'] = 'user';
$t['group'] = 'group';
$t['login_enter'] = 'Enter &gt;&gt;';
$t['login_aaieere'] = 'Log in by using electronic identity in the Eduroam system &gt;&gt;';
$t['login_localoo'] = 'Log in with local user name and password &gt;&gt;';
$t['fsb'] = 'Faculty of Mechanical Engineering and Naval Architecture';
$t['usern']['ameuuu'] = 'Cassword:';
