<?php

// Generated by Transtable - 2013-03-15 18:19:42

$t['sdfsdfsdfsdfsdf'] = 'Log in by using electronic identity in the Eduroam system &gt;&gt;';
$t['sfgh'] = 'Faculty of Mechanical Engineering and Naval Architecture';
$t['zzzzz'] = 'sdfasdfasdfasdfasdf asd fasd fsdfsdfsdfsdf';
$t['asdfasdfsssdsdsd'] = 'asdasdasdasdasdasd';
