<?php

// Generated by Transtable - 2013-03-15 13:36:17

$t['login_aai'] = 'Log in by using electronic identity in the Eduroam system &gt;&gt;';
$t['zzzzzzzzzzzz'] = 'sdfasdfasdfasdfasdf asd fasd fsdfsdfsdfsdf';
$t['asdfasdfsssdsdsd'] = 'asdasdasdasdasdasd';
