<?php

// Generated by Transtable - 2013-03-11 19:55:01

// Translations
$t['wwwwww'] = 'tt';
$t['wwwwwwwww_eee'] = 'oo';
$t['wwwwwwwww']['eee'] = 'uuuuuuuuuuuuuuuu';
$t['wwwwwwwww']['eeexx']['esssee'] = 'eefuuu';
