<?php

// Generated by Transtable - 2013-03-14 17:34:20

$t['user'] = 'user';
$t['login_aai'] = 'Log in by using electronic identity in the Eduroam system &gt;&gt;';
$t['login_local'] = 'Log in with local user name and password &gt;&gt;';
$t['fsb'] = 'Faculty of Mechanical Engineering and Naval Architecture';
$t['zzzzzzzzzzzz'] = 'sdfasdfasdfasdfasdf asd fasd fsdfsdfsdfsdf';
$t['sssdsdsd'] = 'asdasdasdasdasdasd';
